#!/usr/bin/env bash

CFLAGS="-Werror -Wall -Wextra -Wunreachable-code -pedantic -ggdb -fsanitize=address"


gcc $CFLAGS -g $1 && chmod +x ./a.out 

if [ "$2" == "-mem" ] || [ "$3" == "-mem" ]; then
    valgrind -s --leak-check=yes ./a.out 
else
    ./a.out
fi

if [ "$2" == "-rm" ] || [ "$3" == "-rm" ]; then
    rm ./a.out
fi
